WebApp/LibraryMVC/Controllers/BooksController.cs
using LibraryMVC.Domain.Entities;
using LibraryMVC.Domain.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace LibraryMVC.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly IUsersRepository _userRepository;

        public BooksController(IBookRepository bookRepository, IUsersRepository userRepository)
        {
            _bookRepository = bookRepository;
            _userRepository = userRepository;
        }

        public IActionResult List()
        {
            var books = _bookRepository.GetBooks();
            return View(books);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddBookModel book)
        {
            if (ModelState.IsValid)
            {
                _bookRepository.Add(book.Name, book.Author, book.NumberAllBooks);
                return RedirectToAction("List");
            }
            return View(book);
        }

        public IActionResult Delete()
        {
            var books = _bookRepository.GetBooks();
            return View(books);
        }
       
    }

    public class AddBookModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public int NumberAllBooks { get; set; }
    }
}

WebApp/LibraryMVC/Controllers/UsersController.cs
using LibraryMVC.Domain.Entities;
using LibraryMVC.Domain.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace LibraryMVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUsersRepository usersRepository;

        public UsersController(IUsersRepository _usersRepository)
        {
            usersRepository = _usersRepository;
        }

        public IActionResult Activation()
        {
            var users = usersRepository.GetUsers();
            return View(users);
        }

        public IActionResult List()
        {
            var users = usersRepository.GetUsers();
            return View(users);
        }

        [HttpPost]
        public IActionResult Add(AddUserModel user)
        {
            if (ModelState.IsValid)
            {
                usersRepository.Add(user.FirstName, user.LastName);
                return RedirectToAction("List");
            }
            return View(user);
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult BorrowingUser()
        {
            return View();
        }
    }
    public class AddUserModel
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
    }
}

WebApp/LibraryMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryMVC</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(function () {
            var message = "Wróć do mnie!!";
            var original;

            $(window).focus(function () {
                if (original) {
                    document.title = original;
                }
            }).blur(function () {
                var title = $('title').text();
                if (title != message) {
                    original = title;
                }
                document.title = message;
            });
        });
    </script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")" class="navbar-brand">LibraryMVC</a></li>
                    <li><a href="@Url.Action("Index", "Home")">Main page</a></li>
                    <li><a href="@Url.Action("About", "Home")">About us</a></li>
                    <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial");
            </div>
        </div>
    </nav>

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                
                <ul class="nav nav-sidebar">
                    <li class="sidebar-header">Books</li>
                    <li class="sidebar-item active">@Html.ActionLink("List", "List", "Books")</li>
                    <li class="sidebar-item active">@Html.ActionLink("Add", "Add", "Books")</li>
                    <li class="sidebar-item active">@Html.ActionLink("Borrow book", "SelectUser", "BorrowBook")</li>
                    <li class="sidebar-item active">@Html.ActionLink("Return book", "SelectBorrowingUser", "BorrowBook")</li>
                    <li class="sidebar-item active">@Html.ActionLink("Borrowing history", "BorrowingHistory", "BorrowBook")</li>
                    <li li class="sidebar-header">Users</li>
                    <li class="sidebar-item active">@Html.ActionLink("List", "List", "Users")</li>
                    <li class="sidebar-item active">@Html.ActionLink("Add", "Add", "Users")</li>
                    <li class="sidebar-item active">@Html.ActionLink("Activation / deactivation", "Activation", "Users")</li>
                </ul>
            </div>
            <div class="col-sm-9 col-md-10 main">
                
                @RenderBody()
            </div>
        </div>

        <hr />
        <footer>
            <p>&copy; 2020 - LibraryMVC</p>
        </footer>

    </div>
</body>
</html>